import { useCallback, useRef, useState } from 'react';
import type { ExportFormat, Filament, Settings } from '../lib/types';

export type ExportState = 'idle' | 'exporting' | 'done' | 'error';

// ─── Export flow ─────────────────────────────────────────────────────────────
// ⚠️ PLACEHOLDER (V-MODEL-07). The prototype only simulated export with a
// setTimeout — no real STL/3MF/ZIP geometry is produced here either. The
// lithophane mesh is generated by the Rust CLI in /rust; wiring this hook to a
// backend endpoint or a WASM build is the open Phase 6 decision documented in
// docs/frontend/02-offene-punkte-und-vereinfachungen.md.
//
// The state machine and call signature are real so swapping in the actual
// implementation later touches only the body of `runExport`.

export interface ExportRequest {
  settings: Settings;
  filaments: Filament[];
  format: ExportFormat;
  image: { name: string } | null;
}

export function useExport() {
  const [exportState, setExportState] = useState<ExportState>('idle');
  const [exportFormat, setExportFormat] = useState<ExportFormat>('3mf');
  const timers = useRef<number[]>([]);

  const runExport = useCallback((req: ExportRequest) => {
    if (!req.image || exportStateBusy(req)) return;
    setExportState('exporting');
    // TODO(V-MODEL-07): replace the simulated delay with a real generate call.
    timers.current.push(window.setTimeout(() => setExportState('done'), 1800));
    timers.current.push(window.setTimeout(() => setExportState('idle'), 4000));
  }, []);

  return { exportState, exportFormat, setExportFormat, runExport };
}

// Local guard kept tiny and pure; the page also disables the button.
function exportStateBusy(_req: ExportRequest): boolean {
  return false;
}
